using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using backend.Domain.Entities;
using backend.Features.CollectionFeature.CreateCollection;
using backend.Infrastructure.Persistence;
using backend.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace backend.Tests.Features.CollectionFeature;

[Collection("Database")]
public class CreateCollectionHandlerTests(DatabaseFixture fixture)
{
    private async Task<Product> CreateTestProductAsync(AppDbContext context, string name)
    {
        var product = new Product
        {
            NameEn = name,
            Slug = name.ToLower().Replace(" ", "-"),
            Status = "active",
            Price = 99.99m,
            Currency = "IQD",
            CreatedAt = DateTime.Now
        };
        context.Products.Add(product);
        await context.SaveChangesAsync();
        return product;
    }

    [Fact]
    public async Task Handle_ValidCommand_ReturnsSuccess()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(
            NameEn: "Summer Sale",
            NameAr: "تخفيضات الصيف",
            DescriptionEn: "Great summer deals",
            CollectionType: "manual"
        );

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("Summer Sale", result.Value.NameEn);
        Assert.Equal("تخفيضات الصيف", result.Value.NameAr);
        Assert.Equal("summer-sale", result.Value.Slug);
        Assert.True(result.Value.Id > 0);
    }

    [Fact]
    public async Task Handle_WithProducts_CreatesAssociations()
    {
        await using var context = fixture.CreateContext();
        var p1 = await CreateTestProductAsync(context, "Product X " + Guid.NewGuid());
        var p2 = await CreateTestProductAsync(context, "Product Y " + Guid.NewGuid());

        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(
            NameEn: "Featured Products " + Guid.NewGuid(),
            NameAr: null,
            Products: new List<CollectionProductInput>
            {
                new(p1.Id, 10),
                new(p2.Id, 20)
            }
        );

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal(2, result.Value.Products.Count);
        Assert.Equal(p1.Id, result.Value.Products[0].ProductId);
        Assert.Equal(10, result.Value.Products[0].SortOrder);
        Assert.Equal(p2.Id, result.Value.Products[1].ProductId);
        Assert.Equal(20, result.Value.Products[1].SortOrder);
    }

    [Fact]
    public async Task Handle_DuplicateName_ReturnsConflict()
    {
        await using var context = fixture.CreateContext();
        var name = "Duplicate Col " + Guid.NewGuid();
        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(NameEn: name);

        await handler.Handle(command, CancellationToken.None);
        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("already exists", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_InvalidType_ReturnsBadRequest()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(
            NameEn: "Invalid Type Col",
            CollectionType: "invalid-type"
        );

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("Invalid collection type", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_NonExistentProduct_ReturnsNotFound()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(
            NameEn: "Non Existent Product Col " + Guid.NewGuid(),
            Products: new List<CollectionProductInput> { new(999999, 1) }
        );

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("do not exist", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_SlugAutoGeneratedFromNameEn_WhenSlugNotProvided()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(NameEn: "Computers & Gaming " + Guid.NewGuid());

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.StartsWith("computers-gaming", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_CustomSlugProvided_UsesNormalizedSlug()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCollectionHandler(context);
        var command = new CreateCollectionCommand(
            NameEn: "Custom Slug Col " + Guid.NewGuid(),
            Slug: "My Custom Col SLUG!!"
        );

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("my-custom-col-slug", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_DuplicateSlug_AppendsNumberSuffix()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCollectionHandler(context);
        var slug = "dup-slug-" + Guid.NewGuid().ToString("N");

        var first = await handler.Handle(
            new CreateCollectionCommand("Col A", null, Slug: slug),
            CancellationToken.None);

        var second = await handler.Handle(
            new CreateCollectionCommand("Col B", null, Slug: slug),
            CancellationToken.None);

        Assert.True(first.IsSuccess);
        Assert.True(second.IsSuccess);
        Assert.Equal(slug, first.Value!.Slug);
        Assert.Equal($"{slug}-2", second.Value!.Slug);
    }
}
