using backend.Common.Results;
using MediatR;

namespace backend.Features.ProductFeature.UpdateProduct;

public record UpdateProductCommand(
    long Id,
    string NameEn,
    string? NameAr,
    long? CategoryId,
    long? BrandId,
    string? Slug,
    string? Sku,
    string? Barcode,
    string? DescriptionEn,
    string? DescriptionAr,
    string? ShortDescriptionEn,
    string? ShortDescriptionAr,
    decimal Price,
    decimal? CompareAtPrice,
    decimal? CostPrice,
    string Currency,
    int StockQuantity,
    int LowStockThreshold,
    int MinOrderQuantity,
    decimal? Weight,
    string Status,
    bool IsFeatured,
    bool RequiresShipping,
    int WarrantyMonths,
    string? WarrantyDescription,
    string? MetaTitle,
    string? MetaDescription) : IRequest<Result<UpdateProductResponse>>;

public record UpdateProductRequest(
    string NameEn,
    string? NameAr,
    long? CategoryId,
    long? BrandId,
    string? Slug,
    string? Sku,
    string? Barcode,
    string? DescriptionEn,
    string? DescriptionAr,
    string? ShortDescriptionEn,
    string? ShortDescriptionAr,
    decimal Price,
    decimal? CompareAtPrice,
    decimal? CostPrice,
    string Currency,
    int StockQuantity,
    int LowStockThreshold,
    int MinOrderQuantity,
    decimal? Weight,
    string Status,
    bool IsFeatured,
    bool RequiresShipping,
    int WarrantyMonths,
    string? WarrantyDescription,
    string? MetaTitle,
    string? MetaDescription);

public record UpdateProductResponse(
    long Id,
    long? CategoryId,
    long? BrandId,
    string NameEn,
    string? NameAr,
    string Slug,
    string? Sku,
    string? Barcode,
    string? DescriptionEn,
    string? DescriptionAr,
    string? ShortDescriptionEn,
    string? ShortDescriptionAr,
    decimal Price,
    decimal? CompareAtPrice,
    decimal? CostPrice,
    string Currency,
    int StockQuantity,
    int LowStockThreshold,
    int MinOrderQuantity,
    decimal? Weight,
    string Status,
    bool IsFeatured,
    bool RequiresShipping,
    int WarrantyMonths,
    string? WarrantyDescription,
    int TotalSold,
    int ViewsCount,
    string? MetaTitle,
    string? MetaDescription,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    ProductCategoryInfo? Category,
    ProductBrandInfo? Brand);

public record ProductCategoryInfo(long Id, string NameEn, string? NameAr, string Slug);

public record ProductBrandInfo(long Id, string Name, string Slug);
