using backend.Features.BrandFeature.CreateBrand;
using backend.Tests.Infrastructure;

namespace backend.Tests.Features.BrandFeature;

[Collection("Database")]
public class CreateBrandHandlerTests(DatabaseFixture fixture)
{
    [Fact]
    public async Task Handle_ValidCommand_ReturnsSuccess()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateBrandHandler(context);
        var command = new CreateBrandCommand(
            Name: "ASUS",
            DescriptionEn: "Leading tech brand",
            DescriptionAr: "علامة تقنية رائدة");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("ASUS", result.Value.Name);
        Assert.Equal("asus", result.Value.Slug);
        Assert.True(result.Value.IsActive);
        Assert.True(result.Value.Id > 0);
    }

    [Fact]
    public async Task Handle_SlugAutoGeneratedFromName_WhenSlugNotProvided()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateBrandHandler(context);
        var command = new CreateBrandCommand(Name: "HP Inc.");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("hp-inc", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_CustomSlugProvided_UsesNormalizedSlug()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateBrandHandler(context);
        var command = new CreateBrandCommand(
            Name: "Unique Brand Name",
            Slug: "My Custom SLUG!!");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("my-custom-slug", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_DuplicateSlug_AppendsNumberSuffix()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateBrandHandler(context);

        var first = await handler.Handle(
            new CreateBrandCommand("Brand A", Slug: "slug-brand"),
            CancellationToken.None);

        var second = await handler.Handle(
            new CreateBrandCommand("Brand B", Slug: "slug-brand"),
            CancellationToken.None);

        Assert.True(first.IsSuccess);
        Assert.True(second.IsSuccess);
        Assert.Equal("slug-brand", first.Value!.Slug);
        Assert.Equal("slug-brand-2", second.Value!.Slug);
    }

    [Fact]
    public async Task Handle_InputWithWhitespace_TrimsName()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateBrandHandler(context);
        var command = new CreateBrandCommand(
            Name: "  Trimmed Brand  ",
            WebsiteUrl: "  https://example.com  ");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("Trimmed Brand", result.Value!.Name);
        Assert.Equal("https://example.com", result.Value.WebsiteUrl);
    }

    [Fact]
    public async Task Handle_ReturnsZeroProductCount_ForNewBrand()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateBrandHandler(context);
        var command = new CreateBrandCommand(Name: "Count Test Brand");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal(0, result.Value!._count.Product);
    }
}
