using backend.Features.ProductFeature.CreateProduct;
using backend.Tests.Infrastructure;

namespace backend.Tests.Features.ProductFeature;

[Collection("Database")]
public class CreateProductHandlerTests(DatabaseFixture fixture)
{
    [Fact]
    public async Task Handle_ValidCommand_ReturnsSuccess()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "Gaming Laptop",
            NameAr: "لابتوب ألعاب",
            CategoryId: null,
            BrandId: null,
            Price: 1500m);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("Gaming Laptop", result.Value.NameEn);
        Assert.Equal("لابتوب ألعاب", result.Value.NameAr);
        Assert.Equal("gaming-laptop", result.Value.Slug);
        Assert.Equal("IQD", result.Value.Currency);
        Assert.Equal("active", result.Value.Status);
        Assert.True(result.Value.Id > 0);
    }

    [Fact]
    public async Task Handle_DuplicateSku_ReturnsConflict()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var sku = $"SKU-{Guid.NewGuid():N}";

        await handler.Handle(
            new CreateProductCommand("Product A", null, null, null, Sku: sku, Price: 100),
            CancellationToken.None);

        var result = await handler.Handle(
            new CreateProductCommand("Product B", null, null, null, Sku: sku, Price: 200),
            CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("already exists", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_NonExistentCategoryId_ReturnsNotFound()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "Orphan Product",
            NameAr: null,
            CategoryId: 999999,
            BrandId: null,
            Price: 100);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("not found", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_NonExistentBrandId_ReturnsNotFound()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "No Brand Product",
            NameAr: null,
            CategoryId: null,
            BrandId: 999999,
            Price: 100);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("not found", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_InvalidStatus_ReturnsBadRequest()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "Bad Status Product",
            NameAr: null,
            CategoryId: null,
            BrandId: null,
            Price: 100,
            Status: "invalid");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("status", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_SlugAutoGeneratedFromNameEn_WhenSlugNotProvided()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "Wireless Mouse Pro",
            NameAr: null,
            CategoryId: null,
            BrandId: null,
            Price: 50);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("wireless-mouse-pro", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_CustomSlugProvided_UsesNormalizedSlug()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "Unique Product Name",
            NameAr: null,
            CategoryId: null,
            BrandId: null,
            Slug: "My Custom SLUG!!",
            Price: 100);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("my-custom-slug", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_DuplicateSlug_AppendsNumberSuffix()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);

        var first = await handler.Handle(
            new CreateProductCommand("Slug Test A", null, null, null, Slug: "slug-product", Price: 100),
            CancellationToken.None);

        var second = await handler.Handle(
            new CreateProductCommand("Slug Test B", null, null, null, Slug: "slug-product", Price: 200),
            CancellationToken.None);

        Assert.True(first.IsSuccess);
        Assert.True(second.IsSuccess);
        Assert.Equal("slug-product", first.Value!.Slug);
        Assert.Equal("slug-product-2", second.Value!.Slug);
    }

    [Fact]
    public async Task Handle_InputWithWhitespace_TrimsFields()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateProductHandler(context);
        var command = new CreateProductCommand(
            NameEn: "  Trimmed Product  ",
            NameAr: "  منتج  ",
            CategoryId: null,
            BrandId: null,
            Sku: "  SKU-TRIM  ",
            Price: 100);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("Trimmed Product", result.Value!.NameEn);
        Assert.Equal("منتج", result.Value.NameAr);
        Assert.Equal("SKU-TRIM", result.Value.Sku);
    }
}
