using backend.Features.CategoryFeature.CreateCategory;
using backend.Tests.Infrastructure;

namespace backend.Tests.Features.CategoryFeature;

[Collection("Database")]
public class CreateCategoryHandlerTests(DatabaseFixture fixture)
{
    [Fact]
    public async Task Handle_ValidCommand_ReturnsSuccess()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);
        var command = new CreateCategoryCommand(
            NameEn: "Electronics",
            NameAr: "إلكترونيات",
            DescriptionEn: null,
            DescriptionAr: null,
            ParentId: null);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("Electronics", result.Value.NameEn);
        Assert.Equal("إلكترونيات", result.Value.NameAr);
        Assert.Equal("electronics", result.Value.Slug);
        Assert.True(result.Value.Id > 0);
    }

    [Fact]
    public async Task Handle_DuplicateName_ReturnsConflict()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);
        var command = new CreateCategoryCommand(
            NameEn: "Duplicate Category",
            NameAr: null,
            DescriptionEn: null,
            DescriptionAr: null,
            ParentId: null);

        await handler.Handle(command, CancellationToken.None);
        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("already exists", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_NonExistentParentId_ReturnsNotFound()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);
        var command = new CreateCategoryCommand(
            NameEn: "Child Category With Bad Parent",
            NameAr: null,
            DescriptionEn: null,
            DescriptionAr: null,
            ParentId: 999999);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.False(result.IsSuccess);
        Assert.Contains("not found", result.Error, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task Handle_SlugAutoGeneratedFromNameEn_WhenSlugNotProvided()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);
        var command = new CreateCategoryCommand(
            NameEn: "Home & Garden",
            NameAr: null,
            DescriptionEn: null,
            DescriptionAr: null,
            ParentId: null);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("home-garden", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_CustomSlugProvided_UsesNormalizedSlug()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);
        var command = new CreateCategoryCommand(
            NameEn: "Unique Name For Slug Test",
            NameAr: null,
            DescriptionEn: null,
            DescriptionAr: null,
            ParentId: null,
            Slug: "My Custom SLUG!!");

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("my-custom-slug", result.Value!.Slug);
    }

    [Fact]
    public async Task Handle_DuplicateSlug_AppendsNumberSuffix()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);

        var first = await handler.Handle(
            new CreateCategoryCommand("Slug Test A", null, null, null, null, Slug: "slug-test"),
            CancellationToken.None);

        var second = await handler.Handle(
            new CreateCategoryCommand("Slug Test B", null, null, null, null, Slug: "slug-test"),
            CancellationToken.None);

        Assert.True(first.IsSuccess);
        Assert.True(second.IsSuccess);
        Assert.Equal("slug-test", first.Value!.Slug);
        Assert.Equal("slug-test-2", second.Value!.Slug);
    }

    [Fact]
    public async Task Handle_WithExistingParent_AssignsParentId()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);

        var parent = await handler.Handle(
            new CreateCategoryCommand("Parent Cat", null, null, null, null),
            CancellationToken.None);

        var child = await handler.Handle(
            new CreateCategoryCommand("Child Cat", null, null, null, ParentId: parent.Value!.Id),
            CancellationToken.None);

        Assert.True(child.IsSuccess);
        Assert.Equal(parent.Value.Id, child.Value!.ParentId);
    }

    [Fact]
    public async Task Handle_InputWithWhitespace_TrimsName()
    {
        await using var context = fixture.CreateContext();
        var handler = new CreateCategoryHandler(context);
        var command = new CreateCategoryCommand(
            NameEn: "  Trimmed Name  ",
            NameAr: "  اسم  ",
            DescriptionEn: null,
            DescriptionAr: null,
            ParentId: null);

        var result = await handler.Handle(command, CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("Trimmed Name", result.Value!.NameEn);
        Assert.Equal("اسم", result.Value.NameAr);
    }
}
